In [72]:
from random import*
from numpy import*

from sage.all import*
     
pieces = zeros((2, 4), int) 
piecesInGame = []
piecesInGame.append([])
piecesInGame.append([])

finish = [0, 0]

firstMove(pieces, piecesInGame, 1)
print pieces
print piecesInGame
print "\n"
gra(pionki, pionkiWGrze, 1)

print pionki
print pionkiWGrze

'''
while(max(finish1 and finish2)!=4):
    gra(1)
    gra(2)
'''

[[0 0 0 0]
 [4 0 0 0]]
[[], [0]]


[[0 0 0 0]
 [5 0 0 0]]
[[], [0]]


'\nwhile(max(finish1 and finish2)!=4):\n    gra(1)\n    gra(2)\n'